// src/components/Footer.vue
<template>
  <footer class="container">
    <a class="text-dark m-1" href="https://t.me/idevmans" target="_blank">
      Разработал Aidiev Mansur &copy;
      <span>{{ startYear }} - {{ currentYear }}</span>
    </a>
  </footer>
</template>

<script>
export default {
  name: "Footer",
  data() {
    return {
      currentYear: new Date().getFullYear(),
      startYear: 2019
    }
  }

}
</script>

<style scoped>

</style>

// react/src/components/Footer.tsx
function footer() {
    return (
        <footer className="container">
            <a href="https://vk.com/idevmans" className="text-dark m-1" target="_blank">
                Разработал Aydiev Mansur &copy;
                <span>
                        2019 -
                        <script>document.write(new Date().getFullYear())</script>
                    </span>
            </a>
        </footer>
    )
}

export default footer
